import type { Metadata } from "next";
import { Barlow_Condensed, Bellefair, Barlow } from "next/font/google";
import "./globals.css";

const barlow = Barlow({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Space Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className}`}>{children}</body>
    </html>
  );
}
