import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Your Destination",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="destination">{children}</div>;
}
